apiVersion: 1

datasources:
  # Prometheus 数据源
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Loki 数据源
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  # Jaeger 数据源
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false
